language: node_js
sudo: false

node_js:
- '6.15.1'      #boron
- '8.14.0'      #carbon
- '10.14.2'     #dubnium
- stable

script:
  - npm run prepublish-prod

after_success:
- if [ $TRAVIS_NODE_VERSION = 'stable' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
- if [ $TRAVIS_NODE_VERSION = 'stable' ]; then npm run coveralls; fi

env:
  global:
    secure: YqYJyund91Z0PgdBq3S+kCflBhdVVj87INov5eD5b1R2waWUY9fzvifte2t7s9MhI06nspidyyJM9iA2js4As0+gZTG+doa3sc7hEbHurf/mpsmw5c2GGrll9lm3Av2rWMYBIEnffQL1MK7ieTPZLJEJ18Xchjc4a2l/gCdJzhOIzPIWZHLuhm4Td6dJbnw2NRu64VDPabXs89xzL83nZlwKOc0CM/CGroH0NNHI675gqkGUNebp0nH+cosiEbrx5hZNEJNndVNkt1qlifYwGxIx42HLmmLbtCHxbXoup1fmqp7VAYPu1SF7gHcNGyGEC6EWrZQ+BtAzJ0D+ywiZgQqyzIr/eSNbJNcCaUXAB4Cd+S//WtbPH8vVfvZLykGrHEar53k+SXzpLFZzcRfFTCBbPcoE/5EhPoCXIbaLoB453zDJqBVFlIhiVJY7NQYYvVj0FrRnALoFMNFR3xm10wCE1KD5vJbZBiZGjFs+OfsaZ+neyLF3tYCRWtG3MZypEhw9ncMMP4f+5rjsVqNZlUBgD5bzbGFlSCVkCRT92HK1qyOhgm4Gxu801LJeePtlLfD2ZUDPdMswiwo5shS3bC+cIMQeFjU/ArDy+RmIzoHiACIzWcGgj+F7/4OB9NA7qNJGFILP6F6+RIfPG5IguPPlL77ACo7Ki7/Zqya0Lx4=
