# .travis.yml
language: node_js

sudo: false

node_js:
  - "0.12"
  - "4"
  - "5"
  - "stable"
  - "iojs"

after_success:
  - if [ $TRAVIS_NODE_VERSION = 'stable' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
  - if [ $TRAVIS_NODE_VERSION = 'stable' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then npm run coveralls; fi
